java -jar compiler.jar --js_output_file glshooter.min.js \
    --language_in ECMASCRIPT5 \
    --compilation_level ADVANCED_OPTIMIZATIONS \
    --externs lib/tmlib.js \
    --externs lib/gl-matrix.js \
    --externs lib/bulletml.js \
    --js mylib/bulletml.gl2d.js \
    --js mylib/scene.js \
    --js mylib/sprite.js \
    --js mylib/util.js \
    --js game/background.js \
    --js game/bomb.js \
    --js game/boss.js \
    --js game/enemy-data.js \
    --js game/explosion.js \
    --js game/labels.js \
    --js game/main.js \
    --js game/patterns.js \
    --js game/player.js \
    --js game/scenes.js \
    --js game/stage-data.js