zip gl-shooter.zip \
    Background.js \
    explosion.js \
    se_maoudamashii_explosion05.mp3 \
    Player.js \
    shader.fs \
    Scene.js \
    gl-matrix-min.js \
    shader.vs \
    Sprite.js \
    bomb.js \
    boss.js \
    stage-data.js \
    boss1.png \
    index.html \
    texture0.png \
    boss2.png \
    main.js \
    tmlib.js \
    boss3.png \
    nc17909.mp3 \
    util.js \
    bulletml.gl2d.js \
    nc28689.mp3 \
    voice_extend.mp3 \
    bulletml.js \
    nc784.mp3 \
    voice_gen-bomb.mp3 \
    effect0.mp3 \
    patterns.js \
    enemy-data.js \
    scenes.js
